### ISSUE TITLE
Multiple CronJobs with same object of class

### ISSUE THREAD

**Issue by markofranjic** [changhuixu/dotnetlabs#15]
Hi Chan,

Could you please give me information if I can run more then one background jobs with same object of class.
For example. I need to run job at 21:00 and same job need to be run at 05:00?

I have tried 
`  services.AddCronJob<MyCronJob>(c =>
            {
                c.TimeZoneInfo = TimeZoneInfo.Local;
                c.CronExpression = @"{21:00 Time Example}";
            });

            services.AddCronJob<MyCronJob>(c =>
            {
                c.TimeZoneInfo = TimeZoneInfo.Local;
                c.CronExpression = @"{05:00 Time Example}";
            });`

Regards

**Comment by changhuixu** [comment]
Hi @markofranjic 
It's a question about CRON expression. You can use the following configuration.
```csharp
services.AddCronJob<MyCronJob>(c =>
{
     c.TimeZoneInfo = TimeZoneInfo.Local;
     c.CronExpression = @"0 5,21 * * *";
});
```
I did a preliminary test, and it worked. You should test on your own. Let me know what you find out.

**Comment by markofranjic** [comment]
> Hi @markofranjic
> It's a question about CRON expression. You can use the following configuration.
> 
> ```cs
> services.AddCronJob<MyCronJob>(c =>
> {
>      c.TimeZoneInfo = TimeZoneInfo.Local;
>      c.CronExpression = @"0 5,21 * * *";
> });
> ```
> 
> I did a preliminary test, and it worked. You should test on your own. Let me know what you find out.

Is that will be run twice on a day? I ask for that because I need run job on the same day at 5AM and 21PM.

Regards
